config/routes.rb
Rails.application.routes.draw do
  resources :maps
  resources :locations
  resources :rogues
  resources :heros
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hero.rb
class Hero < ApplicationRecord
    has_one :location
    has_one :map, through: :location
    belongs_to :user
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: %i[ show edit update destroy ]

  # GET /heros or /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1 or /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros or /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: "Hero was successfully created." }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1 or /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: "Hero was successfully updated." }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1 or /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: "Hero was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hero_params
      params.require(:hero).permit(:name, :health, :attack, :special, :spc_atk, :status)
    end
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/heros/_form.html.erb
<%= form_with(model: hero) do |form| %>
  <% if hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
        <% hero.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :health %>
    <%= form.number_field :health %>
  </div>

  <div class="field">
    <%= form.label :attack %>
    <%= form.number_field :attack %>
  </div>

  <div class="field">
    <%= form.label :special %>
    <%= form.text_field :special %>
  </div>

  <div class="field">
    <%= form.label :spc_atk %>
    <%= form.number_field :spc_atk %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/heros/edit.html.erb
<h1>Editing Hero</h1>

<%= render 'form', hero: @hero %>

<%= link_to 'Show', @hero %> |
<%= link_to 'Back', heros_path %>

app/views/heros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Heros</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Health</th>
      <th>Attack</th>
      <th>Special</th>
      <th>Spc atk</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.name %></td>
        <td><%= hero.health %></td>
        <td><%= hero.attack %></td>
        <td><%= hero.special %></td>
        <td><%= hero.spc_atk %></td>
        <td><%= hero.status %></td>
        <td><%= link_to 'Show', hero %></td>
        <td><%= link_to 'Edit', edit_hero_path(hero) %></td>
        <td><%= link_to 'Destroy', hero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hero', new_hero_path %>

app/views/heros/new.html.erb
<h1>New Hero</h1>

<%= render 'form', hero: @hero %>

<%= link_to 'Back', heros_path %>

app/views/heros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hero.name %>
</p>

<p>
  <strong>Health:</strong>
  <%= @hero.health %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @hero.attack %>
</p>

<p>
  <strong>Special:</strong>
  <%= @hero.special %>
</p>

<p>
  <strong>Spc atk:</strong>
  <%= @hero.spc_atk %>
</p>

<p>
  <strong>Status:</strong>
  <%= @hero.status %>
</p>

<%= link_to 'Edit', edit_hero_path(@hero) %> |
<%= link_to 'Back', heros_path %>