config/routes.rb
Rails.application.routes.draw do
  resources :maps
  resources :locations
  resources :rogues
  resources :heros
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rogue.rb
class Rogue < ApplicationRecord
    has_one :location
    has_one :map, through: :location
end

app/controllers/rogues_controller.rb
class RoguesController < ApplicationController
  before_action :set_rogue, only: %i[ show edit update destroy ]

  # GET /rogues or /rogues.json
  def index
    @rogues = Rogue.all
  end

  # GET /rogues/1 or /rogues/1.json
  def show
  end

  # GET /rogues/new
  def new
    @rogue = Rogue.new
  end

  # GET /rogues/1/edit
  def edit
  end

  # POST /rogues or /rogues.json
  def create
    @rogue = Rogue.new(rogue_params)

    respond_to do |format|
      if @rogue.save
        format.html { redirect_to @rogue, notice: "Rogue was successfully created." }
        format.json { render :show, status: :created, location: @rogue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rogue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rogues/1 or /rogues/1.json
  def update
    respond_to do |format|
      if @rogue.update(rogue_params)
        format.html { redirect_to @rogue, notice: "Rogue was successfully updated." }
        format.json { render :show, status: :ok, location: @rogue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rogue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rogues/1 or /rogues/1.json
  def destroy
    @rogue.destroy
    respond_to do |format|
      format.html { redirect_to rogues_url, notice: "Rogue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rogue
      @rogue = Rogue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rogue_params
      params.require(:rogue).permit(:name, :health, :attack, :special, :spc_atk, :location)
    end
end

app/helpers/rogues_helper.rb
module RoguesHelper
end

app/views/rogues/_form.html.erb
<%= form_with(model: rogue) do |form| %>
  <% if rogue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rogue.errors.count, "error") %> prohibited this rogue from being saved:</h2>

      <ul>
        <% rogue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :health %>
    <%= form.number_field :health %>
  </div>

  <div class="field">
    <%= form.label :attack %>
    <%= form.number_field :attack %>
  </div>

  <div class="field">
    <%= form.label :special %>
    <%= form.text_field :special %>
  </div>

  <div class="field">
    <%= form.label :spc_atk %>
    <%= form.number_field :spc_atk %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rogues/edit.html.erb
<h1>Editing Rogue</h1>

<%= render 'form', rogue: @rogue %>

<%= link_to 'Show', @rogue %> |
<%= link_to 'Back', rogues_path %>

app/views/rogues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rogues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Health</th>
      <th>Attack</th>
      <th>Special</th>
      <th>Spc atk</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rogues.each do |rogue| %>
      <tr>
        <td><%= rogue.name %></td>
        <td><%= rogue.health %></td>
        <td><%= rogue.attack %></td>
        <td><%= rogue.special %></td>
        <td><%= rogue.spc_atk %></td>
        <td><%= rogue.location %></td>
        <td><%= link_to 'Show', rogue %></td>
        <td><%= link_to 'Edit', edit_rogue_path(rogue) %></td>
        <td><%= link_to 'Destroy', rogue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rogue', new_rogue_path %>

app/views/rogues/new.html.erb
<h1>New Rogue</h1>

<%= render 'form', rogue: @rogue %>

<%= link_to 'Back', rogues_path %>

app/views/rogues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rogue.name %>
</p>

<p>
  <strong>Health:</strong>
  <%= @rogue.health %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @rogue.attack %>
</p>

<p>
  <strong>Special:</strong>
  <%= @rogue.special %>
</p>

<p>
  <strong>Spc atk:</strong>
  <%= @rogue.spc_atk %>
</p>

<p>
  <strong>Location:</strong>
  <%= @rogue.location %>
</p>

<%= link_to 'Edit', edit_rogue_path(@rogue) %> |
<%= link_to 'Back', rogues_path %>